site_name: Tiled Documentation
site_favicon: http://blog.mapeditor.org/favicon.ico
repo_url: https://github.com/bjorn/tiled
theme: readthedocs
google_analytics: ['UA-380618-1', 'mapeditor.org']
pages:
- Index: index.md
- Manual:
    - Introduction: manual/introduction.md
    - Working with Layers: manual/layers.md
    - Editing Tile Layers: manual/editing-tile-layers.md
    - Working with Objects: manual/objects.md
    - Custom Properties: manual/custom-properties.md
    - Using the Terrain Tool: manual/using-the-terrain-tool.md
    - Using Commands: manual/using-commands.md
    - Keyboard Shortcuts: manual/keyboard-shortcuts.md
- Reference:
    - TMX Map Format: reference/tmx-map-format.md
    - TMX Changelog: reference/tmx-changelog.md
    - Libraries and Frameworks: reference/support-for-tmx-maps.md
extra_css:
    - css/extra.css
markdown_extensions:
  - toc(permalink=true)
